language: scala

jdk:
  - oraclejdk8

script:
  - sbt wootModelJVM/test

# From http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html ...

sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

